package contracts.events;

public enum EventType {
    ORDER_SENT_FOR_APPROVAL,
    ORDER_APPROVED,
    ORDER_REJECTED,
    ORDER_EXECUTION_REQUESTED,
    ORDER_EXECUTION_STARTED,
    ORDER_RESERVATION_RELEASE_REQUESTED,
    STOCK_CAR_RESERVATION_REQUESTED,
    STOCK_CAR_RESERVED,
    STOCK_CAR_RESERVATION_REJECTED,
    STOCK_CAR_WRITE_OFF_REQUESTED,
    STOCK_CAR_WRITTEN_OFF,
    STOCK_CAR_WRITE_OFF_REJECTED
}
