package contracts.events;

public enum EventType {
    CUSTOM_ORDER_PARTS_RESERVATION_REQUESTED,
    CUSTOM_ORDER_PARTS_RESERVATION_COMPLETED,
    CUSTOM_ORDER_PARTS_RESERVATION_REJECTED,
    CUSTOM_ORDER_EXECUTION_REQUESTED,
    CUSTOM_ORDER_EXECUTION_COMPLETED,
    CUSTOM_ORDER_EXECUTION_REJECTED,
    CUSTOM_ORDER_RESERVATION_RELEASE_REQUESTED,
    CUSTOM_ORDER_RESERVATION_RELEASE_COMPLETED,
    CUSTOM_ORDER_RESERVATION_RELEASE_REJECTED,
    STOCK_CAR_RESERVATION_REQUESTED,
    STOCK_CAR_RESERVATION_COMPLETED,
    STOCK_CAR_RESERVATION_REJECTED,
    STOCK_CAR_WRITE_OFF_REQUESTED,
    STOCK_CAR_WRITE_OFF_COMPLETED,
    STOCK_CAR_WRITE_OFF_REJECTED,
    STOCK_CAR_RESERVATION_RELEASE_REQUESTED,
    STOCK_CAR_RESERVATION_RELEASE_COMPLETED,
    STOCK_CAR_RESERVATION_RELEASE_REJECTED
}
